services:
  back-end:  # Service du back-end
    build:
      context: ./back-end       # Répertoire contenant le Dockerfile pour le back-end
      dockerfile: Dockerfile    # Nom du fichier Dockerfile (par défaut "Dockerfile")
    image: softy-pinko-back-end:task4  # Nom et tag de l'image construite
    ports:
      - "5252:5252"             # Mappe le port 5252 du conteneur vers le port 5252 de la machine hôte

  front-end:  # Service du front-end
    build:
      context: ./front-end      # Répertoire contenant le Dockerfile pour le front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4
    ports:
      - "9000:9000"             # Mappe le port 9000 du conteneur vers le port 9000 de la machine hôte
    depends_on:
      - back-end                # Démarre le back-end avant le front-end (ordonnancement)
