services:
  back-end:  # Service du back-end
    build:
      context: ./back-end       # Répertoire contenant le Dockerfile pour le back-end
      dockerfile: Dockerfile    # Nom du fichier Dockerfile (par défaut "Dockerfile")
    image: softy-pinko-back-end:task4  # Nom et tag de l'image construite

  front-end:  # Service du front-end
    build:
      context: ./front-end      # Répertoire contenant le Dockerfile pour le front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4
    depends_on:
      - back-end                # Démarre le back-end avant le front-end (ordonnancement)

  proxy:  # Nouveau service proxy (ex: Nginx)
    build:
      context: ./proxy          # Répertoire contenant le Dockerfile pour le proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task4
    ports:
      - "80:80"                 # Expose uniquement le port 80 à l'extérieur
    depends_on:
      - front-end
      - back-end

